### ISSUE TITLE
수집 데이터 문의 드립니다.

### ISSUE THREAD

**Issue by jaehong-k** [HaloKim/bluehouse_petitions#1]
안녕하세요 선생님,
카이스트 소셜 컴퓨팅 연구실에서 연구하고 있는 석사과정 학생 김재홍이라고 합니다. 멋진, 수집 코드 올려주심에 정말 감사드립니다.
저는 new media and society 라는 SCI 저널에, Moral Emotion과 사람들의 정치 선택과 관련한 논문을 투고 준비중에 있습니다.

이전에 스스로 짠 코드로 21년 10월까지 데이터를 수집했었는데, 현재 청원사이트가 없어져서 글을 남기게 됐습니다.
청원이 마감된 시점에서, 전수 데이터를 사용할 수 있다면 분석과 결과에 신뢰성을 더할 수 있을 것이라 생각합니다.
혹시, 선생님께서 수집한 데이터를 보관중이시라면 데이터를 요청드려도 괜찮을까요?!
논무을 출간하게 된다면, 마땅히 그리고 당연히 선생님의 github 링크를 인용하도록 하겠습니다.

이렇게 갑자기 글을 남기게 되어 죄송하고, 또한 멋진 코드 만들어주심에 감사드립니다.
김재홍 드림
(mail: luke.4.18@kaist.ac.kr, twitter: @JaehongLuke418)

**Comment by jaehong-k** [comment]
선생님 이전에 글 남겼던 사람입니다 :) 멋진 코드 짜주심에 감사드립니다.
국민청원 저장소 url이 변경된 것 같아 글 남깁니다.

기존 url 을 아래처럼 변경하면,
url = "http://webarchives.pa.go.kr/19th/www.president.go.kr/petitions/{}".format(code)
수집이 잘 진행되는 것 같습니다 :)
감사합니다!

**Comment by HaloKim** [comment]
안녕하세요 @kjhkjh95 님

이슈 확인하고 업데이트했습니다~

감사합니다😀
